name: hgnn

method: 'HGNN'
add_self_loop: False
runs: 1
train_prop: 0.8
valid_prop: 0.1
All_num_layers: 3
dropout: 0.0
MLP_hidden: 80
HCHA_symdegnorm: null
alpha_softmax: null       # not needed since running HCHA with use_attention = False
cuda: 0
lr: 0.001
epochs: 2000
display_step: 100
wd: 0.0

path_data: 'data/randhouse_v3/hgraph0.pickle'
save_dir: 'train_results/SYNTH_BENCHMARK/randhouse/hgnn/run0'

seed: 0
save_datestamp: False
save_best: True


defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null  
  run:  
    dir: .