defaults:
  - _self_
  - hgraph: random_house_perturbed
  - model: gcn_resid
  - train: base

save_dir: train_results/debug
save_datestamp: False

hydra:  
  output_subdir: null  
  run:  
    dir: .
  