name: learn_mask_house

load_fn: 'train_results/randhouse_v0/allsettransformer/hgraph0/run0'
load_best: True
motif: house

node_samples: null
node_idxs: null
compute_complement: False

coeffs:
  size: 0.005
  ent: 0.01

num_expansions: 3
lr: 0.01
num_epochs: 400
loss_pred_type: kl_div
scheduler: None
init_strategy: const
sample_with: gumbel_softmax
tau: 1.0
save_every: 25
save_fn: 'explanation_randhouse_v0.json'

seed: 42

log_wandb: False

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null  
  run:  
    dir: .
  