name: learn_mask_house

load_fn: 'train_results/randhouse_v3/allsettransformer/hgraph0/run0'
save_fn: 'train_results/randhouse_v3/allsettransformer/hgraph0/run0/explanation_learnt.json'
# load_fn_model: null
# load_fn_hgraph: null
load_best: True
motif: null

node_samples: null
node_idxs: null
compute_complement: True
save_every: 25

num_expansions: 3

# evaluation
loss_pred_type: kl_div
coeffs:
  size: 0.005
  ent: 0.01

log_wandb: False

defaults:  
  - _self_  
  - expl_method: learn_mask
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null  
  run:  
    dir: .
  