name: commhouse

base: community
motif: house
num_nodes: 400
num_edges: 200
num_motifs: 100
num_motif_types: 1
num_random_edges: 80
deg_random_edges: 2
with_outer_hedge: False
num_inter_edges: 80
features: null