name: random_house_norm_features

base: random
num_nodes: 400
num_edges: 200
num_houses: 100
num_house_types: 1
num_random_edges: 70
deg_random_edges: 2
with_outer_hedge: True

features: multiclass_normal
dim_feat: 16
w: 1.0
sigma: 1.0