name: random_house_multiclass_large

base: random
num_nodes: 800
num_edges: 400
num_houses: 200
num_house_types: 2
num_random_edges: 140
deg_random_edges: 2
with_outer_hedge: True

features: multiclass_normal
dim_feat: 16
w: 1.0
sigma: 1.0